version: '2'
services:
  elasticsearch:
    build: ./elasticsearch-docker
    environment:
        http.host: 0.0.0.0
        transport.host: 127.0.0.1
        xpack.security.enabled: "false"
        ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9200:9200